name: 1

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    runs-on:
      group: ubuntu-runners
      labels: x64
    with:
      upload-artifact: true
