name: 1

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    runs-on:
      group: debian
      labels: debian
    uses: ./.github/workflows/1.yml
    secrets: inherit
    with:
      upload-artifact: true
