name: isart

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/isart-build.yml
    secrets: inherit
    with:
      upload-artifact: true
